### ISSUE TITLE
About tokyo 24/7 dataset

### ISSUE THREAD

**Issue by BinuxLiu** [gmberton/datasets_vg#3]
Thank you for your research work which is amazing.
I have a problem and need your help.
I successfully processed the pitts30k dataset, but I'm having trouble formatting the tokyo 24/7 dataset.
Looking forward to your reply

![image](https://user-images.githubusercontent.com/76985767/189291411-de26f7fc-ba0c-4ae4-8509-3955647e5f06.png)
![image](https://user-images.githubusercontent.com/76985767/189291457-806e87b8-337d-42c3-a4ef-ea5c87f73eba.png)

**Comment by gmberton** [comment]
Hello, I have just pushed a better version of the script, could you try to pull the latest version and run the script again?

**Comment by BinuxLiu** [comment]
Ok! I will try it.

**Comment by BinuxLiu** [comment]
![image](https://user-images.githubusercontent.com/76985767/189465784-4509cc31-8fea-4976-9907-087f0abbd11d.png)
**I think the path is duplicated here.**


![image](https://user-images.githubusercontent.com/76985767/189465953-09ff3ae7-c684-492f-87da-af05daf73767.png)
But I still have the same problem.
Did you encounter this problem when you implemented it?
Maybe there is something wrong with the data I got.
This data has been stored with me for several years, and I don't know if the predecessors have changed it.

**Comment by gmberton** [comment]
Hi, I made a new change to the script, you can pull it again and re-run it. It should print out the path of the image that raises the exception.
I think probably the image is corrupted

**Comment by BinuxLiu** [comment]
![image](https://user-images.githubusercontent.com/76985767/189784517-fdadc5f7-4753-4011-a5dd-b1b1ce33a88c.png)
Hi, There is indeed something wrong with the data I store.
Thank you!
